#!/usr/bin/env python3
"""Build small local reader media while retaining the original recordings.

Requires ffmpeg/ffprobe and Pillow with WebP support. Re-running is safe: newly
authored WAVs are moved to assets/source-recordings and converted; the existing
source recordings remain available for lossless regeneration.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import shutil
import subprocess

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
ASSETS = PUBLIC / "assets"
SOURCE_AUDIO = ROOT / "assets/source-recordings"
MOBILE_MAX_SIDE = 768
SHELF_COVERS = {
    "art/eden-01.webp",
    "art/noah-01.webp",
    "art/jonah/jonah-shore.webp",
}


def probe_duration(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "json", str(path)],
        check=True, capture_output=True, text=True,
    )
    return float(json.loads(result.stdout)["format"]["duration"])


def optimize_audio(source: Path) -> tuple[int, int]:
    relative = source.relative_to(SOURCE_AUDIO)
    destination = ASSETS / relative.with_suffix(".mp3")
    destination.parent.mkdir(parents=True, exist_ok=True)
    # The four Jonah soundscapes are longer, layered recordings. Narration is
    # mono and receives a 48 kb/s CBR stream with an Xing gapless header.
    music = "soundscape" in relative.parts or relative.name.startswith((
        "harbor-calm-surf", "storm-wind-and-rain", "deep-water-prayer", "warm-nineveh-breeze"
    ))
    bitrate = "80k" if music else "48k"
    if not destination.exists():
        temporary = destination.with_suffix(".partial.mp3")
        try:
            subprocess.run([
                "ffmpeg", "-nostdin", "-v", "error", "-y", "-i", str(source),
                "-codec:a", "libmp3lame", "-b:a", bitrate,
                "-ar", "24000", "-ac", "1", "-write_xing", "1", str(temporary),
            ], check=True)
            original_duration = probe_duration(source)
            derived_duration = probe_duration(temporary)
            if abs(original_duration - derived_duration) > 0.003:
                raise ValueError(f"Duration changed: {relative}: {original_duration} -> {derived_duration}")
            temporary.replace(destination)
        finally:
            temporary.unlink(missing_ok=True)
    return source.stat().st_size, destination.stat().st_size


def optimize_images() -> tuple[int, int, int]:
    originals = [p for p in ASSETS.rglob("*") if p.suffix.lower() in {".webp", ".png"}
                 and not p.stem.endswith((".mobile", ".cover"))]
    before = after = 0
    for source in originals:
        relative = source.relative_to(ASSETS).as_posix()
        mobile = source.with_suffix(".mobile.webp")
        with Image.open(source) as image:
            before += source.stat().st_size
            # Three-pose actor atlases need a little more width per cell. Most
            # cutouts occupy less than half the 360 px phone canvas; 640 px
            # retains ample detail at the renderer's bounded 1.5x pixel ratio.
            alpha = "A" in image.getbands()
            max_side = (
                960 if "-poses" in source.stem
                else 640 if alpha and image.width / image.height < 1.5
                else MOBILE_MAX_SIDE
            )
            resized = image.copy()
            resized.thumbnail((max_side, max_side), Image.Resampling.LANCZOS)
            resized.save(mobile, "WEBP", quality=80, method=6, exact=True)
            after += mobile.stat().st_size
            if relative in SHELF_COVERS:
                cover = source.with_suffix(".cover.webp")
                if not cover.exists():
                    resized = image.copy()
                    resized.thumbnail((256, 256), Image.Resampling.LANCZOS)
                    resized.save(cover, "WEBP", quality=82, method=6)
    known = sorted(f"assets/{p.relative_to(ASSETS).as_posix()}" for p in originals)
    covers = sorted(f"assets/{p}" for p in SHELF_COVERS)
    (ROOT / "src/generated-media.ts").write_text(
        "// Generated by scripts/optimize-media.py; keep in sync with public/assets.\n"
        + f"export const mobileImages = new Set<string>({json.dumps(known, indent=2)});\n"
        + f"export const shelfCovers = new Set<string>({json.dumps(covers, indent=2)});\n"
    )
    return len(originals), before, after


def rewrite_references() -> None:
    for file in (PUBLIC / "audio-manifest.json", *(PUBLIC / "books").glob("*.book.json")):
        content = file.read_text()
        # The creator keeps stable hashed media names and asset IDs; only the
        # runtime codec suffix changes.
        modified = content.replace(".wav\"", ".mp3\"")
        if modified != content:
            file.write_text(modified)


def main() -> None:
    moved = 0
    for wav in list(ASSETS.rglob("*.wav")):
        source = SOURCE_AUDIO / wav.relative_to(ASSETS)
        source.parent.mkdir(parents=True, exist_ok=True)
        if source.exists():
            raise FileExistsError(f"Source recording already exists; refusing to overwrite: {source}")
        shutil.move(wav, source)
        moved += 1
    sources = sorted(SOURCE_AUDIO.rglob("*.wav"))
    with ThreadPoolExecutor(max_workers=4) as pool:
        sizes = list(pool.map(optimize_audio, sources))
    rewrite_references()
    image_count, image_before, image_after = optimize_images()
    print(f"Audio: {len(sources)} recordings ({moved} new), {sum(a for a, _ in sizes):,} -> {sum(b for _, b in sizes):,} bytes")
    print(f"Mobile art: {image_count} images, {image_before:,} -> {image_after:,} bytes")


if __name__ == "__main__":
    main()
